"""add sources_used to query_logs

Revision ID: 5d71563b6578
Revises: 3480a4fb049b
Create Date: 2026-08-19 15:05:20.473001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d71563b6578'
down_revision: Union[str, Sequence[str], None] = '3480a4fb049b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('sources_used', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'sources_used')
    # ### end Alembic commands ###
