"""add model_used to query_logs

Revision ID: 8cee758d8260
Revises: 5d71563b6578
Create Date: 2026-08-21 11:13:24.586494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cee758d8260'
down_revision: Union[str, Sequence[str], None] = '5d71563b6578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'model_used')
    # ### end Alembic commands ###
